params:
  seed: ${...seed}

  algo:
    name: a2c_continuous

  model:
    name: continuous_a2c_logstd

  network:
    name: BinPacker_PPO #actor_critic
    separate: False
    multidim: False
    space:
      continuous:
        mu_activation: None
        sigma_activation: None

        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: True
    
    cnn:
      type : conv1d
      permute: False
      convs : 
         [ 
           {
            filters : 5,
            kernel_size: 6,
            strides: 6,
            padding: 0
           },
           {
            filters : 10,
            kernel_size: 6,
            strides: 1,
            padding: 0
           },
           {
            filters : 30,
            kernel_size: 6,
            strides: 1,
            padding: 0
           }
         ]
      activation : relu
      normalization : batch_norm
      initializer:
        name: default
    mlp:
      units: [1024, 512, 256, 128, 64]
      activation: elu
      
      initializer:
        name: default
      normalization: None
      d2rl: True
      regularizer:
        name: None

  load_checkpoint: ${if:${...checkpoint},True,False} # flag which sets whether to load the checkpoint
  load_path: ${...checkpoint} # path to the checkpoint to load

  config:
    name: ${resolve_default:BinPacker,${....experiment}}
    full_experiment_name: ${.name}
    env_name: rlgpu
    multi_gpu: ${....multi_gpu}
    ppo: True
    mixed_precision: True
    normalize_input: True
    normalize_value: True
    value_bootstrap: True
    num_actors: ${....task.env.numEnvs}
    reward_shaper:
      scale_value: 0.1
    normalize_advantage: True
    gamma: 1.0
    tau: 0.95
    learning_rate: 3e-4
    lr_schedule: adaptive
    kl_threshold: 0.008
    score_to_win: 100000 #some big number
    max_epochs: ${resolve_default:100000,${....max_iterations}}
    save_best_after: 50
    grad_norm: 1.0
    entropy_coef: 0.0
    truncate_grads: True
    e_clip: 0.2
    horizon_length: 32
    minibatch_size: 32
    mini_epochs: 8
    critic_coef: 4
    clip_value: True
    seq_len: 14
    bounds_loss_coef: 0.0001

    #player:
      #render: True
      #deterministic: True
      #games_num: 10000000
      #print_stats: True